-- MySQL Script generated by MySQL Workbench
-- 05/20/15 07:40:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CRS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CRS` ;

-- -----------------------------------------------------
-- Schema CRS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CRS` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CRS` ;

-- -----------------------------------------------------
-- Table `CRS`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRS`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(80) NOT NULL,
  `pass_user` VARCHAR(80) NOT NULL,
  `email_user` VARCHAR(80) NOT NULL,
  `rol_user` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRS`.`location` (
  `id_location` INT NOT NULL AUTO_INCREMENT,
  `name_location` VARCHAR(80) NOT NULL,
  `capacity_location` INT NOT NULL,
  PRIMARY KEY (`id_location`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`carType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRS`.`carType` (
  `id_type` INT NOT NULL AUTO_INCREMENT,
  `model_car` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRS`.`car` (
  `id_car` INT NOT NULL AUTO_INCREMENT,
  `daily_rate` DOUBLE NOT NULL,
  `hourly_rate` DOUBLE NOT NULL,
  `color` VARCHAR(25) NOT NULL,
  `id_type` INT NOT NULL,
  PRIMARY KEY (`id_car`),
  CONSTRAINT `id_type`
    FOREIGN KEY (`id_type`)
    REFERENCES `CRS`.`carType` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_type_idx` ON `CRS`.`car` (`id_type` ASC);


-- -----------------------------------------------------
-- Table `CRS`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRS`.`invoice` (
  `id_invoice` INT NOT NULL AUTO_INCREMENT,
  `date_invoice` DATETIME NOT NULL,
  `type_payment` VARCHAR(80) NOT NULL,
  `aval_invoice` VARCHAR(45) NOT NULL,
  `total_cost` DOUBLE NOT NULL,
  PRIMARY KEY (`id_invoice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`serve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRS`.`serve` (
  `id_customer` INT NOT NULL,
  `id_invoice` INT NOT NULL,
  CONSTRAINT `id_invoice`
    FOREIGN KEY (`id_invoice`)
    REFERENCES `CRS`.`invoice` (`id_invoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_customer`
    FOREIGN KEY (`id_customer`)
    REFERENCES `CRS`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_invoice_idx` ON `CRS`.`serve` (`id_invoice` ASC);

CREATE INDEX `id_customer_idx` ON `CRS`.`serve` (`id_customer` ASC);


-- -----------------------------------------------------
-- Table `CRS`.`locationCar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRS`.`locationCar` (
  `id_location` INT NOT NULL,
  `id_car` INT NOT NULL,
  CONSTRAINT `id_location`
    FOREIGN KEY (`id_location`)
    REFERENCES `CRS`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_car`
    FOREIGN KEY (`id_car`)
    REFERENCES `CRS`.`car` (`id_car`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_location_idx` ON `CRS`.`locationCar` (`id_location` ASC);

CREATE INDEX `id_car_idx` ON `CRS`.`locationCar` (`id_car` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
